ESM:
  tree: https://data.nextstrain.org/ncov_gisaid_reference.json
  root: https://data.nextstrain.org/ncov_gisaid_reference_root-sequence.json
  gene: S
  fine_tune: false

latent_diffusion:
  tree: https://data.nextstrain.org/ncov_gisaid_reference.json
  root: https://data.nextstrain.org/ncov_gisaid_reference_root-sequence.json
  gene: nuc
  count: 50
