# Model options: esm2_t33_650M_UR50D, esm2_t36_3B_UR50D, esm2_t48_15B_UR50D

# For fine-tuning ESM on data from 2020 through 2022
ESM_fine_tune:
  dataset: https://nextstrain.org/groups/blab/ncov/gisaid/global/all-time/16k/2023-01-01
  gene: S
  epochs: 3
  batch_size: 8
  model: esm2_t33_650M_UR50D
  model_weights: models/esm.bin

# For estimating Pango lineage embeddings with ESM
ESM_embeddings:
  dataset: https://nextstrain.org/nextclade/sars-cov-2
  gene: S
  model: esm2_t33_650M_UR50D
  model_weights: pretrained # file location for fine tuned model, or "pretrained"
  log_likelihoods: results/log_likelihoods.tsv
  embeddings: results/embeddings.tsv
  ordination: results/ordination.tsv

latent_diffusion:
  dataset: https://nextstrain.org/ncov/gisaid/reference
  gene: nuc
  count: 50
